import numpy as np
import pytest

from LoopStructural.modelling.core.stratigraphic_column import (
    StratigraphicColumn,
    StratigraphicColumnElement,
    StratigraphicColumnElementType,
    StratigraphicGroup,
    StratigraphicUnconformity,
    StratigraphicUnit,
    UnconformityType,
)


# ---------------------------------------------------------------------------
# StratigraphicColumnElement
# ---------------------------------------------------------------------------
class TestStratigraphicColumnElement:
    def test_uuid_autogenerated_and_unique(self):
        a = StratigraphicColumnElement()
        b = StratigraphicColumnElement()
        assert a.uuid is not None
        assert b.uuid is not None
        assert a.uuid != b.uuid

    def test_uuid_can_be_supplied(self):
        element = StratigraphicColumnElement(uuid="my-uuid")
        assert element.uuid == "my-uuid"


# ---------------------------------------------------------------------------
# StratigraphicUnit
# ---------------------------------------------------------------------------
class TestStratigraphicUnit:
    def test_construction_with_explicit_id(self):
        unit = StratigraphicUnit(name="A", thickness=10, id=0)
        assert unit.name == "A"
        assert unit.thickness == 10
        assert unit.id == 0
        assert unit.element_type == StratigraphicColumnElementType.UNIT
        assert unit.data is None

    def test_default_colour_is_random_rgb_triplet(self):
        unit = StratigraphicUnit(name="A", id=0)
        colour = np.asarray(unit.colour)
        assert colour.shape == (3,)
        assert np.all(colour >= 0) and np.all(colour <= 1)

    def test_explicit_colour_preserved(self):
        unit = StratigraphicUnit(name="A", id=0, colour="red")
        assert unit.colour == "red"

    def test_thickness_setter_updates_value(self):
        unit = StratigraphicUnit(name="A", id=0, thickness=5)
        unit.thickness = 15
        assert unit.thickness == 15

    def test_id_setter_rejects_non_integer(self):
        unit = StratigraphicUnit(name="A", id=0)
        with pytest.raises(TypeError):
            unit.id = "not-an-int"

    def test_id_setter_rejects_float(self):
        unit = StratigraphicUnit(name="A", id=0)
        with pytest.raises(TypeError):
            unit.id = 1.5

    def test_min_max_default_when_unset(self):
        unit = StratigraphicUnit(name="A", id=0)
        assert unit.min() == 0
        assert unit.max() == np.inf

    def test_min_max_reflect_assigned_values(self):
        unit = StratigraphicUnit(name="A", id=0)
        unit.min_value = 1.0
        unit.max_value = 2.0
        assert unit.min() == 1.0
        assert unit.max() == 2.0

    def test_to_dict_converts_ndarray_colour_to_list(self):
        unit = StratigraphicUnit(name="A", id=0, thickness=5, colour=np.array([0.1, 0.2, 0.3]))
        d = unit.to_dict()
        assert d["name"] == "A"
        assert d["thickness"] == 5
        assert d["id"] == 0
        assert isinstance(d["colour"], list)
        assert d["colour"] == pytest.approx([0.1, 0.2, 0.3])

    def test_to_dict_preserves_string_colour(self):
        unit = StratigraphicUnit(name="A", id=0, colour="grey")
        d = unit.to_dict()
        assert d["colour"] == "grey"

    def test_from_dict_roundtrip(self):
        original = StratigraphicUnit(name="A", id=3, thickness=7, colour="blue")
        d = original.to_dict()
        restored = StratigraphicUnit.from_dict(d)
        assert restored.name == original.name
        assert restored.thickness == original.thickness
        assert restored.id == original.id
        assert restored.colour == original.colour
        assert restored.uuid == original.uuid

    def test_from_dict_requires_dict(self):
        with pytest.raises(TypeError):
            StratigraphicUnit.from_dict("not-a-dict")

    def test_str_contains_name_colour_thickness(self):
        unit = StratigraphicUnit(name="A", id=0, thickness=5, colour="grey")
        s = str(unit)
        assert "A" in s
        assert "grey" in s
        assert "5" in s

    def test_from_dict_without_id_raises_type_error_bug(self):
        """Documents a bug: StratigraphicUnit.from_dict() (and StratigraphicUnit()
        construction in general) is documented as accepting ``id=None`` by default,
        but the ``id`` property setter unconditionally requires an int:

            if not isinstance(value, int):
                raise TypeError("ID must be an integer")

        Since ``__init__`` always does ``self.id = id`` (even when id is the
        default None), any code path that omits "id" - such as
        StratigraphicUnit.from_dict() being fed a dict without an "id" key, which
        is exactly the shape produced by hand-written/legacy stratigraphic column
        dicts - raises TypeError instead of constructing a unit with some sentinel
        id. This test documents the CURRENT (broken) behaviour.
        """
        with pytest.raises(TypeError):
            StratigraphicUnit.from_dict({"name": "A", "thickness": 5})

    def test_construction_without_id_raises_type_error_bug(self):
        """Same root cause as test_from_dict_without_id_raises_type_error_bug:
        omitting `id` (its documented default) at construction time raises
        TypeError rather than succeeding with an unset/sentinel id.
        """
        with pytest.raises(TypeError):
            StratigraphicUnit(name="A")


# ---------------------------------------------------------------------------
# StratigraphicUnconformity
# ---------------------------------------------------------------------------
class TestStratigraphicUnconformity:
    def test_default_type_is_erode(self):
        unconformity = StratigraphicUnconformity(name="unc")
        assert unconformity.unconformity_type == UnconformityType.ERODE
        assert unconformity.element_type == StratigraphicColumnElementType.UNCONFORMITY

    def test_onlap_type_accepted(self):
        unconformity = StratigraphicUnconformity(name="unc", unconformity_type=UnconformityType.ONLAP)
        assert unconformity.unconformity_type == UnconformityType.ONLAP

    def test_invalid_type_raises_value_error(self):
        with pytest.raises(ValueError):
            StratigraphicUnconformity(name="unc", unconformity_type="bogus")

    def test_to_dict_from_dict_roundtrip(self):
        original = StratigraphicUnconformity(name="unc", unconformity_type=UnconformityType.ONLAP)
        d = original.to_dict()
        assert d == {
            "uuid": original.uuid,
            "name": "unc",
            "unconformity_type": "onlap",
        }
        restored = StratigraphicUnconformity.from_dict(d)
        assert restored.name == original.name
        assert restored.unconformity_type == original.unconformity_type
        assert restored.uuid == original.uuid

    def test_from_dict_requires_dict(self):
        with pytest.raises(TypeError):
            StratigraphicUnconformity.from_dict(["not", "a", "dict"])

    def test_from_dict_defaults_to_erode_when_type_missing(self):
        restored = StratigraphicUnconformity.from_dict({"name": "unc"})
        assert restored.unconformity_type == UnconformityType.ERODE

    def test_str_contains_name_and_type(self):
        unconformity = StratigraphicUnconformity(name="unc", unconformity_type=UnconformityType.ONLAP)
        s = str(unconformity)
        assert "unc" in s
        assert "onlap" in s


# ---------------------------------------------------------------------------
# StratigraphicGroup
# ---------------------------------------------------------------------------
class TestStratigraphicGroup:
    def test_default_construction_empty(self):
        group = StratigraphicGroup()
        assert group.name is None
        assert group.units == []

    def test_units_list_not_shared_between_instances(self):
        group_a = StratigraphicGroup(name="a")
        group_b = StratigraphicGroup(name="b")
        group_a.units.append("unit")
        assert group_b.units == []

    def test_construction_with_units(self):
        group = StratigraphicGroup(name="g", units=[1, 2, 3])
        assert group.name == "g"
        assert group.units == [1, 2, 3]


# ---------------------------------------------------------------------------
# StratigraphicColumn
# ---------------------------------------------------------------------------
class TestStratigraphicColumnConstruction:
    def test_new_column_has_basement_and_base_unconformity(self):
        column = StratigraphicColumn()
        assert len(column.order) == 2
        assert isinstance(column.order[0], StratigraphicUnit)
        assert column.order[0].name == "Basement"
        assert column.order[0].thickness == np.inf
        assert isinstance(column.order[1], StratigraphicUnconformity)
        assert column.order[1].name == "Base Unconformity"
        assert column.order[1].unconformity_type == UnconformityType.ERODE

    def test_get_new_id_starts_at_one_after_basement(self):
        column = StratigraphicColumn()
        # Basement already consumed id 0.
        assert column.get_new_id() == 1

    def test_get_new_id_increments_as_units_added(self):
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        assert column.get_new_id() == 2
        column.add_unit("B", thickness=5)
        assert column.get_new_id() == 3

    def test_get_new_id_reuses_highest_available_after_removal(self):
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        b_unit = column.add_unit("B", thickness=5)
        assert column.get_new_id() == 3
        column.remove_unit(b_unit.uuid)
        assert column.get_new_id() == 2


class TestAddRemoveUnits:
    def test_add_unit_default_appends_to_top(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10)
        assert column.order[-1] is unit
        assert unit.name == "A"
        assert unit.thickness == 10

    def test_add_unit_where_bottom_inserts_at_start(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10, where="bottom")
        assert column.order[0] is unit

    def test_add_unit_invalid_where_raises(self):
        column = StratigraphicColumn()
        with pytest.raises(ValueError):
            column.add_unit("A", thickness=10, where="middle")

    def test_add_unit_explicit_id_used(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10, id=42)
        assert unit.id == 42

    def test_add_unconformity_default_appends_to_top(self):
        column = StratigraphicColumn()
        unconformity = column.add_unconformity("unc1")
        assert column.order[-1] is unconformity
        assert unconformity.unconformity_type == UnconformityType.ERODE

    def test_add_unconformity_where_bottom(self):
        column = StratigraphicColumn()
        unconformity = column.add_unconformity("unc1", where="bottom")
        assert column.order[0] is unconformity

    def test_add_unconformity_invalid_where_raises(self):
        column = StratigraphicColumn()
        with pytest.raises(ValueError):
            column.add_unconformity("unc1", where="middle")

    def test_add_unconformity_onlap_type(self):
        column = StratigraphicColumn()
        unconformity = column.add_unconformity("unc1", unconformity_type=UnconformityType.ONLAP)
        assert unconformity.unconformity_type == UnconformityType.ONLAP

    def test_remove_unit_by_uuid_succeeds(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10)
        assert column.remove_unit(unit.uuid) is True
        assert unit not in column.order

    def test_remove_unit_nonexistent_uuid_returns_false(self):
        column = StratigraphicColumn()
        assert column.remove_unit("does-not-exist") is False

    def test_add_element_accepts_element(self):
        column = StratigraphicColumn()
        column.clear(basement=False)
        element = StratigraphicUnit(name="A", id=0)
        column.add_element(element)
        assert column.order == [element]

    def test_add_element_rejects_non_element(self):
        column = StratigraphicColumn()
        with pytest.raises(TypeError):
            column.add_element("not-an-element")


class TestLookups:
    def test_get_element_by_index_valid(self):
        column = StratigraphicColumn()
        assert column.get_element_by_index(0).name == "Basement"

    def test_get_element_by_index_out_of_range_raises(self):
        column = StratigraphicColumn()
        with pytest.raises(IndexError):
            column.get_element_by_index(100)

    def test_get_element_by_index_negative_raises(self):
        column = StratigraphicColumn()
        with pytest.raises(IndexError):
            column.get_element_by_index(-1)

    def test_get_unit_by_name_found(self):
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        found = column.get_unit_by_name("A")
        assert found is not None
        assert found.name == "A"

    def test_get_unit_by_name_not_found_returns_none(self):
        column = StratigraphicColumn()
        assert column.get_unit_by_name("missing") is None

    def test_get_unit_by_name_ignores_unconformities(self):
        column = StratigraphicColumn()
        assert column.get_unit_by_name("Base Unconformity") is None

    def test_get_unconformity_by_name_found(self):
        column = StratigraphicColumn()
        found = column.get_unconformity_by_name("Base Unconformity")
        assert found is not None

    def test_get_unconformity_by_name_not_found_returns_none(self):
        column = StratigraphicColumn()
        assert column.get_unconformity_by_name("missing") is None

    def test_get_element_by_uuid_found(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10)
        assert column.get_element_by_uuid(unit.uuid) is unit

    def test_get_element_by_uuid_missing_raises_keyerror(self):
        column = StratigraphicColumn()
        with pytest.raises(KeyError):
            column.get_element_by_uuid("missing")

    def test_getitem_matches_get_element_by_uuid(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10)
        assert column[unit.uuid] is unit

    def test_getitem_missing_raises_keyerror(self):
        column = StratigraphicColumn()
        with pytest.raises(KeyError):
            column["missing"]

    def test_get_elements_returns_internal_order(self):
        column = StratigraphicColumn()
        assert column.get_elements() is column.order


class TestGroupsAndSummaries:
    def _build_two_group_column(self):
        column = StratigraphicColumn()
        column.clear(basement=False)
        column.add_unit("A", thickness=10, id=0)
        column.add_unconformity("unc1")
        column.add_unit("B", thickness=5, id=1)
        return column

    def test_get_groups_splits_on_unconformities(self):
        column = self._build_two_group_column()
        groups = column.get_groups()
        assert len(groups) == 2
        # get_groups walks self.order in reverse, so the last-added unit
        # ("B", above the unconformity) forms the first (youngest) group.
        assert [u.name for u in groups[0].units] == ["B"]
        assert [u.name for u in groups[1].units] == ["A"]

    def test_get_groups_default_names(self):
        column = self._build_two_group_column()
        groups = column.get_groups()
        assert groups[0].name == "Group_0"
        assert groups[1].name == "Group_1"

    def test_get_groups_uses_group_mapping_overrides(self):
        column = self._build_two_group_column()
        column.group_mapping = {"Group_0": "Upper", "Group_1": "Lower"}
        groups = column.get_groups()
        assert groups[0].name == "Upper"
        assert groups[1].name == "Lower"

    def test_get_group_for_unit_name(self):
        column = self._build_two_group_column()
        group = column.get_group_for_unit_name("A")
        assert group is not None
        assert any(u.name == "A" for u in group.units)

    def test_get_group_for_unit_name_missing_returns_none(self):
        column = self._build_two_group_column()
        assert column.get_group_for_unit_name("missing") is None

    def test_get_unitname_groups(self):
        column = self._build_two_group_column()
        assert column.get_unitname_groups() == [["B"], ["A"]]

    def test_get_group_unit_pairs(self):
        column = self._build_two_group_column()
        pairs = column.get_group_unit_pairs()
        assert pairs == [("Group_0", "B"), ("Group_1", "A")]

    def test_get_isovalues(self):
        column = self._build_two_group_column()
        isovalues = column.get_isovalues()
        assert set(isovalues.keys()) == {"A", "B"}
        assert isovalues["A"]["value"] == 0
        assert isovalues["A"]["group"] == "Group_1"
        assert isovalues["B"]["value"] == 0
        assert isovalues["B"]["group"] == "Group_0"

    def test_get_isovalues_multi_unit_group(self):
        # Isovalues must match update_unit_values: the base of the oldest
        # unit in a group is 0, and each unit's thickness gives the base
        # value of the next (younger) unit.
        column = StratigraphicColumn()
        column.clear(basement=False)
        column.add_unit("A", thickness=10, id=0)
        column.add_unit("B", thickness=5, id=1)
        column.add_unit("C", thickness=3, id=2)
        isovalues = column.get_isovalues()
        assert isovalues["A"]["value"] == 0
        assert isovalues["B"]["value"] == 10
        assert isovalues["C"]["value"] == 15

    def test_get_isovalues_where_top_returns_unit_top(self):
        # where='top' must give each unit's top, i.e. base + thickness --
        # the same value that where='bottom' (default) gives the next
        # (younger) unit as its base.
        column = StratigraphicColumn()
        column.clear(basement=False)
        column.add_unit("A", thickness=10, id=0)
        column.add_unit("B", thickness=5, id=1)
        column.add_unit("C", thickness=3, id=2)
        isovalues = column.get_isovalues(where='top')
        assert isovalues["A"]["value"] == 10
        assert isovalues["B"]["value"] == 15
        assert isovalues["C"]["value"] == 18

    def test_get_isovalues_invalid_where_raises(self):
        column = self._build_two_group_column()
        with pytest.raises(ValueError):
            column.get_isovalues(where="middle")


class TestOrderingAndUpdates:
    def test_update_order_reorders_elements(self):
        column = StratigraphicColumn()
        column.clear(basement=False)
        a = column.add_unit("A", thickness=10, id=0)
        b = column.add_unit("B", thickness=5, id=1)
        column.update_order([b.uuid, a.uuid])
        assert column.order == [b, a]

    def test_update_order_requires_list(self):
        column = StratigraphicColumn()
        with pytest.raises(TypeError):
            column.update_order("not-a-list")

    def test_update_order_unknown_uuid_raises_keyerror(self):
        column = StratigraphicColumn()
        with pytest.raises(KeyError):
            column.update_order(["missing-uuid"])

    def test_update_unit_values_computes_cumulative_thickness(self):
        column = StratigraphicColumn()
        column.clear(basement=False)
        a = column.add_unit("A", thickness=10, id=0)
        b = column.add_unit("B", thickness=5, id=1)
        column.update_unit_values()
        assert a.min_value == 0
        assert a.max_value == 10
        assert b.min_value == 10
        assert b.max_value == 15

    def test_update_element_updates_unit_fields(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10)
        column.update_element({"uuid": unit.uuid, "name": "A2", "thickness": 20})
        assert unit.name == "A2"
        assert unit.thickness == 20

    def test_update_element_updates_unconformity_fields(self):
        column = StratigraphicColumn()
        unconformity = column.get_unconformity_by_name("Base Unconformity")
        column.update_element(
            {"uuid": unconformity.uuid, "name": "renamed", "unconformity_type": "onlap"}
        )
        assert unconformity.name == "renamed"
        assert unconformity.unconformity_type == UnconformityType.ONLAP

    def test_update_element_requires_dict(self):
        column = StratigraphicColumn()
        with pytest.raises(TypeError):
            column.update_element("not-a-dict")

    def test_update_element_missing_uuid_raises_keyerror(self):
        column = StratigraphicColumn()
        with pytest.raises(KeyError):
            column.update_element({"uuid": "missing", "name": "x"})


class TestNotifications:
    def test_add_unit_notifies_unit_added(self):
        column = StratigraphicColumn()
        events = []

        def callback(observable, event, **kwargs):
            events.append(event)

        column.attach(callback)
        column.add_unit("A", thickness=10)
        assert "unit_added" in events

    def test_add_unconformity_notifies_unconformity_added(self):
        column = StratigraphicColumn()
        events = []

        def callback(observable, event, **kwargs):
            events.append(event)

        column.attach(callback)
        column.add_unconformity("unc")
        assert "unconformity_added" in events

    def test_remove_unit_notifies_unit_removed(self):
        column = StratigraphicColumn()
        unit = column.add_unit("A", thickness=10)
        events = []

        def callback(observable, event, **kwargs):
            events.append(event)

        column.attach(callback)
        column.remove_unit(unit.uuid)
        assert "unit_removed" in events

    def test_clear_notifies_column_cleared(self):
        column = StratigraphicColumn()
        events = []

        def callback(observable, event, **kwargs):
            events.append(event)

        column.attach(callback)
        column.clear(basement=False)
        assert "column_cleared" in events


class TestSerialization:
    def test_column_to_dict_contains_all_elements(self):
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        d = column.to_dict()
        assert len(d["elements"]) == len(column.order)
        names = [e["name"] for e in d["elements"]]
        assert names == ["Basement", "Base Unconformity", "A"]

    def test_column_from_dict_roundtrip(self):
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        column.add_unit("B", thickness=5)
        d = column.to_dict()
        restored = StratigraphicColumn.from_dict(d)
        assert [e.name for e in restored.order] == [e.name for e in column.order]
        for original_element, restored_element in zip(column.order, restored.order):
            assert type(original_element) is type(restored_element)

    def test_from_dict_requires_dict(self):
        with pytest.raises(TypeError):
            StratigraphicColumn.from_dict("not-a-dict")

    def test_update_from_dict_replaces_contents(self):
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        other = StratigraphicColumn()
        other.clear(basement=False)
        other.add_unit("C", thickness=1, id=0)
        column.update_from_dict(other.to_dict())
        assert [e.name for e in column.order] == ["C"]

    def test_update_from_dict_requires_dict(self):
        column = StratigraphicColumn()
        with pytest.raises(TypeError):
            column.update_from_dict("not-a-dict")


class TestMiscellaneous:
    def test_str_lists_elements_in_order(self):
        column = StratigraphicColumn()
        column.clear(basement=False)
        column.add_unit("A", thickness=10, id=0)
        s = str(column)
        assert s.startswith("1. ")
        assert "A" in s

    def test_cmap_converts_non_string_colours_to_hex(self):
        column = StratigraphicColumn()
        column.clear(basement=False)
        column.add_unit("A", thickness=10, id=0, colour=[0.1, 0.2, 0.3])
        unit = column.get_unit_by_name("A")
        column.cmap()
        assert isinstance(unit.colour, str)
        assert unit.colour.startswith("#")

    def test_plot_returns_figure_when_no_axis_given(self):
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        column = StratigraphicColumn()
        column.clear(basement=False)
        column.add_unit("A", thickness=10, id=0)
        column.add_unit("B", thickness=5, id=1)
        fig = column.plot()
        assert fig is not None
        plt.close(fig)


# ---------------------------------------------------------------------------
# Regression tests for bugs that were previously present in this module.
# These document the FIXED (correct) behaviour; see git history for the
# characterization tests that used to document the broken behaviour.
# ---------------------------------------------------------------------------
class TestFixedBugs:
    def test_clear_with_basement_true_restores_basement(self):
        """``clear(basement=True)`` (the default) must leave the column with
        just the Basement unit and Base Unconformity, not empty.
        """
        column = StratigraphicColumn()
        column.add_unit("A", thickness=10)
        assert len(column.order) > 0

        column.clear()  # basement=True by default

        assert len(column.order) == 2
        assert column.order[0].name == "Basement"
        assert column.order[1].name == "Base Unconformity"

    def test_unit_min_max_not_poisoned_by_basement_infinite_thickness(self):
        """The basement unit is always created with ``thickness=np.inf``.

        ``update_unit_values()`` resets its cumulative thickness accumulator
        at each unconformity, so the basement's infinite thickness is
        contained within its own group (isolated by the Base Unconformity)
        and does not leak into the min/max range of real units added above
        it.
        """
        column = StratigraphicColumn()  # includes basement with thickness=inf
        unit = column.add_unit("A", thickness=10)

        assert unit.min() == 0
        assert unit.max() == 10

    def test_thickness_setter_live_updates_min_max(self):
        """``StratigraphicColumn.add_unit()`` does::

            unit.attach(self.update_unit_values, 'unit/*')

        ``self.update_unit_values`` is a bound method; ``Observable.attach()``
        tracks bound-method listeners via ``weakref.WeakMethod`` (keyed on the
        owning instance) rather than a plain weak reference to the transient
        bound-method wrapper, so the subscription survives. Changing
        ``unit.thickness`` after the unit has been added to a column
        therefore automatically refreshes downstream ``min_value``/
        ``max_value`` without an explicit call to
        ``column.update_unit_values()``.
        """
        column = StratigraphicColumn()
        column.clear(basement=False)
        a = column.add_unit("A", thickness=10, id=0)
        b = column.add_unit("B", thickness=5, id=1)
        assert a.max_value == 10
        assert b.min_value == 10
        assert b.max_value == 15

        a.thickness = 100  # should cascade to b's min/max

        assert b.min_value == 100
        assert b.max_value == 105
