{% set name = "loopstructural" %}
{% set version = load_setup_py_data().version %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Loop3D/LoopStructural
  # git_tag: lg_development

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  build:
    - Cython
  host:
    - pip
    - python
    - cython
    - setuptools
    - numpy
  # run:
  #   - Cython
  #   - numpy
  #   - pandas
  #   - scipy
  #   - matplotlib
  #   - scikit-image
  #   - scikit-learn
# test:
#   imports:
#     - LoopStructural


about:
  home: "https://github.com/Loop3D/LoopStructural"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Implicit 3D geological modelling library"
  doc_url: "https://loop3d.github.io/LoopStructural/"
  dev_url: 

extra:
  recipe-maintainers:
    - lachlangrose