name: "🎳 Tester"

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - .github/workflows/tester.yml
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - .github/workflows/tester.yml
  workflow_dispatch:

jobs:
  continuous-integration:
    name: Continuous integration ${{ matrix.os }} python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(vars.BUILD_OS) }}
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies and library
        run: |
          uv pip install --user \
            numpy \
            scipy \
            scikit-image \
            scikit-learn \
            pytest \
            networkx \
            osqp \
            matplotlib \
            -e .[tests]

      - name: pytest
        run: |
          pytest
